"""add hashed_password and is_admin to employee

Revision ID: 76fdc4e22893
Revises: de5acd33db37
Create Date: 2026-08-17 07:57:29.225910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fdc4e22893'
down_revision: Union[str, None] = 'de5acd33db37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('is_admin', sa.String(length=1), server_default='N', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_admin')
    op.drop_column('employees', 'hashed_password')
    # ### end Alembic commands ###
